version: '2'
services:
  dbapi:
    image: stackdump/pstack-pgsql:latest
    build:
      context: .
      dockerfile: ./dbapi/Dockerfile
    hostname: dbapi
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pstack
      POSTGRES_PASSWORD: pstack
      POSTGRES_DB: pstack
      PYTHONDEBUG: 1
      FACTOMD_ENDPOINT: http://factomd:8088/v2
  wsapi:
    image: stackdump/pstack-wsapi:latest
    build:
      context: ./wsapi
    hostname: wsapi
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
      PGUSER: pstack
      PGPASSWORD: pstack
      PGHOST: dbapi
      PGDATABASE: pstack
    depends_on:
      - dbapi
